### ISSUE TITLE
Segfault when installing Chromium beta

### ISSUE THREAD

**Issue by cassidyjames** [elementary/sideload#104] opened 2020-11-15 06:44 UTC
## What Happened

I opened https://flathub.org/beta-repo/appstream/org.chromium.Chromium.flatpakref in Sideload and tried to install it. After confirming I wanted to install, the app closed. In Terminal, I see a segmentation fault.

## Expected Behavior

Chromium either installs or Sideload provides an intelligible error. 

## Steps to Reproduce

1. Download https://flathub.org/beta-repo/appstream/org.chromium.Chromium.flatpakref
2. Open the flatpakref
3. Confirm you want to install it

## Platform Information

elementary OS 6 daily build

**Comment by meisenzahl** [comment] 2020-11-15 07:26
Can confirm

## Platform Information

elementary OS 6 daily build

**Comment by davidmhewitt** [comment] 2020-11-15 11:48
This is a duplicate of #96 but #105 is marked to close both :)

**Closed** 2020-11-15 21:59 UTC
Labels: Status: Confirmed
